Always allow running commands using node or id regardless config
Issue:
If users import the vmss info and then try to use --node or --id, then
the command will fail because we will have vmss info + node or vmss info
+ resource-id and it will not know what to select.

Solution:
Don't read the current config vmss info if node or id was specified. It
is not needed anyway.

Initial state:

$ ./kubectl-aks config import

Let's say aks-nodepool1-17267820-vmss000002 is the node I need to use more frequently:

$ ./kubectl-aks config use-node aks-nodepool1-17267820-vmss000002

However, if I need to run one single command in node aks-nodepool1-17267820-vmss000000

Before this PR:

$ ./kubectl-aks check-apiserver-connectivity --node
aks-nodepool1-17267820-vmss000000
Error: specify either 'node' or VMMS instance information ('subscription', 'node-resource-group', 'vmss' and 'instance-id')

After this PR:

$ ./kubectl-aks check-apiserver-connectivity --node
aks-nodepool1-17267820-vmss000000
Connectivity check: succeeded

Signed-off-by: Jose Blanquicet <josebl@microsoft.com>